PRIMARY_COLOR = "#4906d0"
PRIMARY_COLOR_HOVER = "#350596"
SECONDARY_COLOR = "#999999"
BACKGROUND_COLOR = "#fff"
INPUT_COLOR = BACKGROUND_COLOR

TITLE_FONT = ("Arial", 24, "bold")
LABEL_FONT = ("Arial", 14, "bold")
